//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Мероприятия1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Мероприятия
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Мероприятия()
        {
            this.Активности = new HashSet<Активности>();
        }
    
        public int Код_мероприятия { get; set; }
        public string Событие { get; set; }
        public string Дата { get; set; }
        public int Дни { get; set; }
        public int Город { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Активности> Активности { get; set; }
        public virtual Города Города { get; set; }
    }
}
