//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Мероприятия1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Пользователи
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Пользователи()
        {
            this.Активности = new HashSet<Активности>();
            this.Активности1 = new HashSet<Активности>();
            this.Активности2 = new HashSet<Активности>();
            this.Активности3 = new HashSet<Активности>();
            this.Активности4 = new HashSet<Активности>();
            this.Активности5 = new HashSet<Активности>();
            this.Активности6 = new HashSet<Активности>();
        }
    
        public int Код_пользователи { get; set; }
        public string ФИО { get; set; }
        public string пол { get; set; }
        public string почта { get; set; }
        public System.DateTime дата_рождения { get; set; }
        public int страна { get; set; }
        public string телефон { get; set; }
        public string направление { get; set; }
        public string мероприятие { get; set; }
        public string уникальный_код { get; set; }
        public string пароль { get; set; }
        public string фото { get; set; }
        public int код_роли { get; set; }
    
        public virtual Cтраны Cтраны { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Активности> Активности { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Активности> Активности1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Активности> Активности2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Активности> Активности3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Активности> Активности4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Активности> Активности5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Активности> Активности6 { get; set; }
        public virtual Роли Роли { get; set; }
    }
}
